### ISSUE TITLE
Import errors have no message

### ISSUE THREAD

**Issue by themerk** [typesense/typesense-js#104]
`ImportError` throws with no message. It looks like this line should be `super(message)`

https://github.com/typesense/typesense-js/blob/3d7c270aea427fd6b2e96abe6ba0712d58fa8273/src/Typesense/Errors/ImportError.ts#L6-L9

I was thoroughly confused about what was going wrong in my import because I couldn't see this (very helpful) error message:
https://github.com/typesense/typesense-js/blob/7cc70b4dc658c9335d586c705c58cf2123f3d317/src/Typesense/Documents.ts#L227-L232

**Comment by jasonbosco** [comment]
@themerk Thank you for catching this 🙏 

I've fixed it [here](https://github.com/typesense/typesense-js/commit/a88e4fc33bff29a8735d4b074bebbdcfcabfb884#diff-37a47e0f5ac5429409cd1e6e96d1493a2e454c8913cdcef772954a0b2aec06abR7) and pushed this out in v1.1.4-0. Could you give it a shot now and confirm if the error message shows up now?

**Comment by themerk** [comment]
@jasonbosco that's awesome, I appreciate the quick fix! Yep, I can confirm that error message now comes through.
