### ISSUE TITLE
group_by is keyof T while in documentation is it a string

### ISSUE THREAD

**Issue by orasik** [typesense/typesense-js#105]
## Description

I was trying to group a search by a field that is defined as a facet when I had an error in the editor:

```
Argument of type '{ q: string; query_by: string; group_by: string; group_limit: string; }' is not assignable to parameter of type 'SearchParams<{}>'.
  Types of property 'group_by' are incompatible.
    Type 'string' is not assignable to type 'never'.ts(2345)
```
I am using typescript.

## Steps to reproduce

1. Create a search client.
2. Create a `searchParam` object:
```
	let searchParameters = {
		q: req.params.location,
		query_by: 'city',
		group_by: 'state',
		group_limit: '1',
	};
```

## Expected Behavior

It should not raise any errors when using Typescript.

## Actual Behavior

Error:

```
Argument of type '{ q: string; query_by: string; group_by: string; group_limit: string; }' is not assignable to parameter of type 'SearchParams<{}>'.
  Types of property 'group_by' are incompatible.
    Type 'string' is not assignable to type 'never'.ts(2345)
```
## Documentation

[Search Parameters - Grouping ](https://typesense.org/docs/0.22.2/api/documents.html#search-parameters)

## Metadata

**Typsense Version**: 1.1.2

**OS**: Mac M1Pro

**Comment by jasonbosco** [comment]
@orasik Thank you for catching this. I've pushed out a fix in `v1.1.3`.
