### ISSUE TITLE
prefix for multiple fields in search parameters is not possible

### ISSUE THREAD

**Issue by orasik** [typesense/typesense-js#109]
## Description

According to the [search parameters](https://typesense.org/docs/0.22.2/api/documents.html#search-parameters) docs, we can define the behavior of prefix for multiple fields such as `prefix=true,false,true`.

However, this is not doable as `prefix` is defined as a boolean variable in the [SearchParams](https://github.com/typesense/typesense-js/blob/master/src/Typesense/Documents.ts#L37).

I tried to add `?prefix=true` in the `query_by` but that didn't work either.

**Comment by jasonbosco** [comment]
@orasik I've fixed this in `1.1.4-2` so you can now use a boolean or string for `prefix`. Could you give it a shot now?

**Comment by orasik** [comment]
@jasonbosco looking good now. Thanks!
