### ISSUE TITLE
allowed types for SearchParams['query_by'] don't match documentation

### ISSUE THREAD

**Issue by olve** [typesense/typesense-js#120]
## Description
according to [docs](https://typesense.org/docs/0.22.2/api/documents.html#search), SearchParams['query_by'] accepts string arrays, however the type-definitions provided are limited to `string` only.

**Comment by jasonbosco** [comment]
@olve The docs say "One or more `string` / `string[]` fields that should be queried against. Separate multiple fields with a comma: `company_name, country`".

So the actual value for `query_by` needs to be a comma separated string (not an array). It's just that the data type for the field names used in the query_by param can be strings or arrays of strings.
