### ISSUE TITLE
404 attempting to delete document with ID containing "#" hash symbol

### ISSUE THREAD

**Issue by stildalf** [typesense/typesense-js#131]
## Description

Trying to delete a single document with a string ID containing a *#* symbol returns a 404. Deleting a document with string ID sans the # works just fine. Seems to be trimming the ID from first # occurrence onward - so `ABC#DEF123` gets trimmed to `ABC` and no such document is found to be deleted.  

Not sure whether the problem lies upstream or not, thought I'd post here first.

No issues with inserting or searching for documents with these IDs, nor deleting a whole collection containing docs with IDs as described.

## Steps to reproduce

* Insert some documents to a collection with string IDs containing the hash symbol
* Attempt a document delete:  
`client.collections('companies').documents('ABC#DEF123').delete()`

## Expected Behavior

Successful document deletes for string IDs containing the # symbol.

## Actual Behavior
```
ObjectNotFound: Request failed with HTTP code 404 | Server said: Could not find a document with id: ABC
    at ObjectNotFound.TypesenseError [as constructor] (~/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23:28)
    at new ObjectNotFound (~/node_modules/typesense/lib/Typesense/Errors/ObjectNotFound.js:25:42)
    at ApiCall.customErrorForResponse (~/node_modules/typesense/lib/Typesense/ApiCall.js:334:21)
    at ~/node_modules/typesense/lib/Typesense/ApiCall.js:195:98
    at step (~/node_modules/typesense/lib/Typesense/ApiCall.js:33:23)
    at Object.next (~/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at step (~/node_modules/typesense/lib/Typesense/ApiCall.js:18:139)
    at Object.next (~/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at fulfilled (~/node_modules/typesense/lib/Typesense/ApiCall.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  httpStatus: 404
}
```
Note the trimmed ID in the error. Requested delete of `ABC#DEF123`, reports 404 on `ABC`.

## Metadata

**Typsense Version**: docker typesense/typesense:0.23.0 & 0.23.1
**typesense-js Version**: 1.3.0 & 1.4.0
**OS**: Ubuntu 20.04.4 LTS
**Node Version**: 16.16.0

**Comment by jasonbosco** [comment]
@stildalf Could you try this:

```js
client.collections('companies').documents(encodeURIComponent('ABC#DEF123')).delete()
```

**Comment by stildalf** [comment]
Thanks @jasonbosco , just tried and worked.

Apologies, should've tried something like that before posting.

Any documentation or pointers we can refer to regarding having to encode document IDs?

**Comment by jasonbosco** [comment]
No worries! Your post will now help future searchers, so thank you for posting it :)

The ID format is documented in the yellow "Note" section here: https://typesense.org/docs/0.23.1/api/documents.html#index-documents

> The `id` should not include spaces or any other characters that require encoding in urls.

While that's a general recommendation, if you do use a character that requires URL encoding, then you would have to URL encode it before making any API calls that have the ID in the URL.

**Comment by stildalf** [comment]
Perfect, couldn't be clearer.

I would've sworn I read (obviously glossed) over that doc page 5 times today. 

Thanks again, appreciate the nudge forwards.
