### ISSUE TITLE
Regex syntax error?

### ISSUE THREAD

**Issue by nandorojo** [typesense/typesense-js#133]
## Description

Hey, so I'm not 100% sure if this issue is caused by Typesense yet, but since I added a Typesense `facet_query` search to a screen, I started getting it on Sentry. Does something like this look familiar?

```
SyntaxError: Invalid regular expression: missing )
```

Sorry this issue is half-baked, I'm trying to get to the bottom of this and wanted to see if it looked like something that could be related to Typesense. I'm grasping at straws here, but could it be [this line](https://github.com/typesense/typesense-js/blob/ebc360a5c916c246c473119b287573ad1a00169f/dist/typesense.js#L984)?

## Steps to reproduce

TBD, trying to reproduce still. It's inconsistent, but judging from user sessions it happens when people are typing in an input for a facet search.

## Expected Behavior

N/A

## Actual Behavior

```
SyntaxError: Invalid regular expression: missing )
```

## Metadata

**Typsense Version**: 1.4.0

**OS**:

MacOS

**Comment by jasonbosco** [comment]
@nandorojo The line you linked to isn't actually part of the Typesense source code - it's coming from a dependency. 

typesense-js itself doesn't use any RegEx.

**Comment by nandorojo** [comment]
Got it, must not be related then. Thanks for letting me know.

**Comment by nandorojo** [comment]
Do you by chance know what that dependency is doing in that line? When users are searching `remixes` or `salsa`, I'm seeing this crash (but only sometimes):

<img width="920" alt="image" src="https://user-images.githubusercontent.com/13172299/186706136-5b759824-ee6d-4b8b-893a-3db3e85490e6.png">

Is it possible that dependency is getting used to construct URLs or something?

It feels unlikely that it's related, I also don't use any `RegExp` in my app, so I am trying to find the issue anywhere I can...

Appreciate your time here.

**Comment by nandorojo** [comment]
Ah, sorry, disregard this. I think it's related to a dependency I have which I just found and removed. Thanks again.
