### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by sbleh** [typesense/typesense-js#137]
Encountered the following model error in the `SearchResponseHit['highlights'][0]`:

- `indices` is modeled as `string[]` while it's a `number[]`
- `matched_tokens` is modeled as `string[]` while its a `string[][]` array

**Comment by sbleh** [comment]
@jasonbosco looks good to me, thanks for the fast fix. And of course, `matched_tokens` can be `string[]` and `string[][]`.

**Comment by jasonbosco** [comment]
Thank you for confirming!
