### ISSUE TITLE
Retrieve stats.json via client?

### ISSUE THREAD

**Issue by paulsingh** [typesense/typesense-js#138]
This isn't an issue per se... more of a question: I see that the client can retrieve Health and Metrics, is there a reason that Stats (eg, stats.json) isn't also available?

**Comment by jasonbosco** [comment]
We were thinking about potentially merging the stats and metrics endpoint at some point in the future on the Typesense Server side... So we didn't add it to the clients until we've finalized on what we want to do there.

**Comment by julianpoy** [comment]
Any update on this?

**Comment by flowluap** [comment]
Also interested in this topic.

**Comment by jasonbosco** [comment]
The stats endpoint is now available in `1.9.0-3`:

`client.stats.retrieve()`
