### ISSUE TITLE
Export documents fails for large data sets (1.6million records)

### ISSUE THREAD

**Issue by Bug-Reaper** [typesense/typesense-js#140]
## Description

[Export documents](https://typesense.org/docs/0.23.1/api/documents.html#export-documents) fails completely for large collections (memory issue). 

I'd guess this is related to the fact that the method tries to return a string and so at some point must put all the collection's documents into memory. The default max-memory-per-variable/max-string-length are fairly low in both JS/Node-JS. 

## Potential Fix

It'd be great if this method could return a ReadableStream instead? 

Or maybe add a very similar sister function that returns a stream instead of a string? 
Something like:
`client.collections('companies').documents().exportAsStream()`
 
## Screenshot

![image](https://user-images.githubusercontent.com/31227781/202629611-1cc32402-46be-443f-bd64-23127daf9759.png)

## Steps to reproduce
Export a sufficiently large collection. (Mine was 1.6 million records)

## Expected Behavior

Be able to export all documents in a collection.

## Actual Behavior

Node-JS hits a memory related error

**Typesense Version**:
Latest

**OS**:
Linux/MacOS

**Comment by jasonbosco** [comment]
@Bug-Reaper There's already an `exportStream` method: https://github.com/typesense/typesense-js/blob/b0854ab5829b6819e82b6fa9d3304643b9d0772e/src/Typesense/Documents.ts#L255
