### ISSUE TITLE
400 error with update(..., { filter_by })

### ISSUE THREAD

**Issue by jdriscoll98** [typesense/typesense-js#170]
## Description

Getting an error when trying out "Update by query" function from v0.25.0

RequestMalformed: Request failed with HTTP code 400 | Server said: For update, the `id` key must be provided.

## Steps to reproduce

Here is my code:

```
  let document = {
    seller_type: 'dealer',
  };
  await client.collections('products_alias').documents().update(document, {
    filter_by: `seller_id:=${id}`,
  });
  ```

## Expected Behavior

To update all documents that match a given filter_by query:

## Actual Behavior

RequestMalformed: Request failed with HTTP code 400 | Server said: For update, the `id` key must be provided.

## Metadata

**Typesense Version**: v0.25.0
**Typesense JS Version**: v1.7.1

**OS**: Mac Ventura 13.2.1

**Comment by jasonbosco** [comment]
This is a duplicate of https://github.com/typesense/typesense/issues/1165. Will fix it shortly.

**Comment by jdriscoll98** [comment]
@jasonbosco Thank you! I'll close this one and follow that
