### ISSUE TITLE
Missing Pagination Params `offset` and `limit`

### ISSUE THREAD

**Issue by danimt** [typesense/typesense-js#172]
## Description

From v0.25.0 two new params were added: `offset` and `limit`.
https://typesense.org/docs/latest/api/search.html#pagination-parameters

## Expected Behavior

Add new params to `SearchParams` interface.
https://github.com/typesense/typesense-js/blob/master/src/Typesense/Documents.ts#L37

Possibly other places might need it as well.
e.g. https://github.com/typesense/typesense-js/blob/master/src/Typesense/Documents.ts#L138

## Actual Behavior

Parameters are missing.

**Comment by jasonbosco** [comment]
@danimt Could you try this with `v1.7.2-1`?
