### ISSUE TITLE
PresetSchema is declared as id but api returns name

### ISSUE THREAD

**Issue by bfritscher** [typesense/typesense-js#190]
## Description
Request Payload definition in typings does not match return value of API.

## Steps to reproduce
query the presets api
<img width="267" alt="image" src="https://github.com/typesense/typesense-js/assets/338973/e7133b51-f175-4a0a-b9de-ee70081efa7d">

<img width="388" alt="image" src="https://github.com/typesense/typesense-js/assets/338973/590b622e-5ca4-42fe-a82f-61927559bc80">

## Expected Behavior

API and typings should match

## Actual Behavior
mismatch, type has to be overriden to make a typescript application work

## Metadata

**Typesense Version**: 0.25.2
**Typesense Client**: 1.7.2

**Comment by jasonbosco** [comment]
Could you submit a PR for this?
