### ISSUE TITLE
Schema metadata is missing on create/update collection

### ISSUE THREAD

**Issue by onhate** [typesense/typesense-js#197]
## Description

Schema metadata is missing on create/update collection

https://typesense.org/docs/26.0/api/collections.html#adding-metadata-to-schema

## Metadata

**Typesense SDK**: 1.8.2

**Comment by onhate** [comment]
Looks like it's just a type issue on the CollectionSchema and respective update create types, right?

**Comment by jasonbosco** [comment]
Yeah, it's a typing issue. 

I've added these in `1.8.3-0`. Could you check now?

**Comment by onhate** [comment]
it works now @jasonbosco thank you!
