### ISSUE TITLE
[React Native] filter_by := not woking on iOS 17.4

### ISSUE THREAD

**Issue by Namnp1521** [typesense/typesense-js#206]
## Description

I cannot get no result when use filter `:=` on iOS 17.4. But if i use `filter_by:[abc, def]`, it's work. So i dont know  `:=` not wok
i still get the result with lower iOS version :((

![image](https://github.com/typesense/typesense-js/assets/45452919/6122fec6-d172-43d9-b424-db2e4c7b4570)

my package:
"react": "18.1.0",
"react-native": "0.70.0",
"typesense": "^1.5.2"

**Comment by jasonbosco** [comment]
I suspect this is similar to URL encoding, very similar to #193. 

Could you follow the same solution mentioned here: https://github.com/typesense/typesense-js/issues/193#issuecomment-1930763613

**Comment by Namnp1521** [comment]
it works, thank you so much

> I suspect this is similar to URL encoding, very similar to #193.
> 
> Could you follow the same solution mentioned here: [#193 (comment)](https://github.com/typesense/typesense-js/issues/193#issuecomment-1930763613)

it works, thank you so much!

**Comment by jasonbosco** [comment]
Here's another work-around that allows you use to use multi_search: https://github.com/typesense/typesense-js/issues/193#issuecomment-2132638054
