### ISSUE TITLE
Alphanumeric search issue 

### ISSUE THREAD

**Issue by mannywebdev** [typesense/typesense-js#219]
## Description
I am searching for product code which is in formats "665A", "665V", "66589" 

## Expected Behavior

It has to give all three if I search for "665" 

## Actual Behavior

But its giving the last one "66589" but not giving "665A", "665V". Basically when its alphabets, are there its not giving results

## Metadata

**Typesense Version**:

**OS**:

**Comment by mannywebdev** [comment]
No infix search required in my case.

**Comment by jasonbosco** [comment]
Could you try setting `max_candidates: 10000`?

**Comment by mannywebdev** [comment]
Thanks @jasonbosco. It worked like a charm.

**Comment by mannywebdev** [comment]
Worked with the suggested approach.
