### ISSUE TITLE
How To support array of objects search field types  ?

### ISSUE THREAD

**Issue by ibrahimBelk** [typesense/typesense-js#25]
I have a json file which contains an array of objects and I want to crearte a schema for that so how to do it ?

**Comment by kishorenc** [comment]
@ibrahimBelk You have to use type as `string[]` when you [define the schema](https://github.com/typesense/typesense-js/blob/master/doc/examples/server/collections.js#L40).

**Comment by rohit-gh** [comment]
Are we talking about json objects? Can't we search on array of strings?

**Comment by kishorenc** [comment]
Array of strings are fine! Just define the type as `string[]`.

**Comment by PMLS3** [comment]
@kishorenc I received this error:  Field `attributes` must be an array of string.
My array: 
  attributes: [
>      {
>        omni_id: 'iSyTHsYA3HXg20cTLoUX',
>        visible: true,
>        woo_id: '',
>        name: 'Colours',
>        options: [Array],
>        position: 1,
>        slug: 'colours',
>        variation: true
>      },
>      {
>        omni_id: 'tq6QDbEi81ypTW7vKaR4',
>        visible: true,
>        woo_id: '',
>        name: 'Weights',
>        options: [Array],
>        position: 2,
>        slug: 'weights',
>        variation: true
>      },
>      {
>        omni_id: 'uLJtADx9zCrTjnYzLZbc',
>        visible: true,
>        woo_id: '',
>        name: 'Sizes',
>        options: [Array],
>        position: 3,
>        slug: 'sizes',
>        variation: true
>      }
>    ],


  {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "attributes",
      "optional": true,
      "sort": false,
      "type": "string[]"
    },
    
What am I doing wrong?
