### ISSUE TITLE
Errors should return code

### ISSUE THREAD

**Issue by goliatone** [typesense/typesense-js#41]
Currently errors do not seem to include the API error code, [just a message](https://github.com/typesense/typesense-js/blob/master/src/Typesense/ApiCall.js#L88).

**Comment by jasonbosco** [comment]
@goliatone Good catch. I've added custom error objects and a new field called `httpStatus` in [`v0.7.0-2`](https://www.npmjs.com/package/typesense/v/0.7.0-2). 

Here's an example of how to use this: https://github.com/typesense/typesense-js/blob/9ac12dcb75f4d068087ad4cb89e92e1c9608818a/doc/examples/server/errorHandling.js#L24-L38

Side note: `v0.7.0-2` is a pre-release version that is only compatible with Typesense Server v0.15 which is around the corder. You can grab a release candidate of v0.15 from this docker image: `docker pull typesense/typesense:0.15.0.rc25`

**Comment by jasonbosco** [comment]
v0.7.0 is now published and addresses this.
