### ISSUE TITLE
Feature request: make client http proxy friendly, omit port if undefined

### ISSUE THREAD

**Issue by fabien** [typesense/typesense-js#42]
I'm using Typesense through a HTTP proxy at a specific path (example: https://example.com/typesense). In this case it's not desirable that a port is required when specifying such a node:

https://github.com/typesense/typesense-js/blob/ed1b22d8e5405544c3c2fd5c971cd853106bf98a/src/Typesense/ApiCall.js#L179

Could this be accounted for in an upcoming release?

**Comment by jasonbosco** [comment]
@fabien Just published `v0.7.1` with this update. Port is now optional and will default to 80 or 443 based on the protocol specified.
