### ISSUE TITLE
NPM Release does not contain updated 0.9.0 code

### ISSUE THREAD

**Issue by fabien** [typesense/typesense-js#46]
## Description

The version installed by npm is outdated and doesn't include the latest code in `lib`. For example, the new `documents().delete()` method is undefined. NPM only includes the `lib` directory, no source or anything else.

## Steps to reproduce

`npm install typesense-js@0.9.0`

**Comment by fabien** [comment]
@jasonbosco @kishorenc any update on this?

**Comment by jasonbosco** [comment]
@fabien Sorry about that, I forgot to run `npm run build` before publishing 🤦. Just published v0.9.1 with the fix.
