### ISSUE TITLE
Backend InstantSearch Support

### ISSUE THREAD

**Issue by hadminh** [typesense/typesense-js#72]
## Feature Request

Thank you for this awesome library. Please look at this issue as a feature request.

## Description

I was trying to follow Algolia's [Backend InstantSearch](https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/react) guide but I faced some issue. I finally managed to make it work but I had to add extra fields like `nbHits`, `hitsPerPage`, `nbPages`, `objectID` to the returned results to make it work.

```
const Typesense = require("typesense");
const typesense = new Typesense.Client({
  nodes: [{ host: "*****.ngrok.io", port: "443", protocol: "https" }],
  apiKey: "xyz",
});
export default async function handler({ body }, res) {
  const { requests } = body;
  const typesenseResults = await typesense.multiSearch.perform({
    searches: requests,
  });
  const results = {
    ...typesenseResults,
    results: typesenseResults.results.map((result) => ({
      ...result,
      nbHits: result.found,
      nbPages: result.out_of,
      hitsPerPage: 9,
      hits: result.hits.map((hit) => ({
        ...hit,
        objectID: hit.document.id,
        document: { ...hit.document },
      })),
    })),
  };
  res.status(200).send(results);
}

```

Are you planning to make an adaptor for the TypesenseClient library to return the same results as Algolia's client library does?

`algoliaClient.searchForFacetValues(requests);`
`algoliaClient.search(requests);`

## Use Case

I use this feature to add and remove unnecessary data for performance reasons. As well as in house built-in authorization to prevent an unauthenticated user to access certain fields.

**Comment by jasonbosco** [comment]
@hadminh Have a look at this repository: https://github.com/typesense/typesense-instantsearch-adapter, specifically the `SearchResponseAdapter.js`. It essentially converts the Typesense API response into Algolia API format. 

It was meant to be used with Instantsearch on the frontend, but you can also use it on the backend. 

Does that work?

**Comment by hadminh** [comment]
Thanks, for the quick reply. It technically should work. But this library doesn't expose a publicly accessible method [typesense/typesense-instantsearch-adapter](https://github.com/typesense/typesense-instantsearch-adapter)

Please Note that this is a three step method:
1) We convert From `InstantSearch Query` To `Typesense Query` Format, either on the client or on the server.
2) We make an Api call on the backend to the `Typesense` DB
3) Convert the `Typesense` response to `Algolia` friendly response 

```
// 1. Convert from InstantSearch query to Typesense query
const { body } = JSON.parse(req);
const convertInstantSearchToTypense = new SearchRequestAdapter(
  body
).request();

// 2. Make an Api call to Typesense backend using the converted query

const typesenseResponse = await typesense.multiSearch.perform({
  searches: convertInstantSearchToTypense,
});
// 3. Convert from Typesense response to Algolia response and send back the response to client

const convertTypesenseToInstantSearch = new SearchResponseAdapter(
  typesenseResponse
).adapt();

res.status(200).send(convertTypesenseToInstantSearch);
```

**Comment by hadminh** [comment]
Yes it is possible the following does the trick no need for the `SearchRequestAdapter`.
The following method `searchTypesenseAndAdapt` is exposed publicly.

```
 const results = await typesenseInstantsearchAdapter.searchTypesenseAndAdapt(
    requests
  );
```
