### ISSUE TITLE
Feedback on TS support

### ISSUE THREAD

**Issue by natac13** [typesense/typesense-js#73]
## Description

Should these deprecated properties be required?

![Screen Shot 2021-10-08 at 09 25 47](https://user-images.githubusercontent.com/10660283/136565221-6c26f455-031a-4b3a-9a26-3910db985461.png)

Is `index` supposed to be required on `Node`?
![Screen Shot 2021-10-08 at 09 26 18](https://user-images.githubusercontent.com/10660283/136565301-d2ad794b-cc08-4f31-a657-7c0ad31072a0.png)
![Screen Shot 2021-10-08 at 09 26 25](https://user-images.githubusercontent.com/10660283/136565321-ddd0086c-7bea-48f4-a0a7-d0ccd12088b4.png)

**Comment by dcantu476** [comment]
I put in another PR for my suggested change. I can go the Node and NodeInternal / InternalNode route if you like. Just let me know!

**Comment by jasonbosco** [comment]
@dcantu476 I like that. How about `NodeConfiguration` in Configuration.ts and just `Node` in ApiCall.ts?

**Comment by dcantu476** [comment]
PR is updated

**Comment by jasonbosco** [comment]
Just released these changes in `v1.0.0-2`.
