### ISSUE TITLE
SearchClient doesn't return type-parameterized Collection

### ISSUE THREAD

**Issue by AadamZ5** [typesense/typesense-js#77]
https://github.com/typesense/typesense-js/blob/100d619d71f17b8b0b935e2ab2974c166dfa184f/src/Typesense/SearchClient.ts#L26-L39

You can see here that `collections(...)` in `SearchClient` does not return a type-parameterized version of `Collection`. This is not similar to the normal `Client` which does allow a type parameter in the `collections(...)` function there.

In `SearchClient`, I think the `collection(...)` function signature should be like this:
```typescript
collections<T extends DocumentSchema = {}>(collectionName: string): Collection<T> { 
  ...
}
```

I stumbled across this issue while trying to make an Angular module for TypeSense. I'd love to release a small Angular wrapper for TypeSense, but the inconsistency with type-generics is holding me back from making a release-ready version. (That's not mentioning that I've never really released a wrapper lib like what I'm working on before, it would be a joy to try)

I'm loving the lightness of TypeSense so far! I can tell that the JS/TS library here is rapidly evolving for the better, and I hope to help! Let me know if me opening a PR would be helpful.

**Comment by jasonbosco** [comment]
> Do `_individualCollections` all have the same DocumentSchema in a SearchClient instance?

One (may be confusing) nuance is that `_individualCollections` stores an array of `Collection` objects, and a `Collection` object in the client library is different from the actual Collection Schema that the user defines in Typesense Server. 

This is the reason the method signature to get the actual server Collection Schema is `client.collections('name').retrieve()`. 

Whereas `client.collections('name')` returns just the `Collection` object in the client library. 

To answer the intent of your original question, all `_individualCollections` do have the same `Collection` type.

It's defined with a stronger type here: 

https://github.com/typesense/typesense-js/blob/8f8f91c128d73598d0f50e73672ac9963ca6c6df/src/Typesense/Client.ts#L24

So I think the following line might have just been an oversight: 

https://github.com/typesense/typesense-js/blob/8f8f91c128d73598d0f50e73672ac9963ca6c6df/src/Typesense/Client.ts#L47

Should be ok to change that to 

```ts
collections<T extends Record<string, Collection> = {}>(collectionName: string): Collection<T>
```

Separately, `SearchClient` is just a subset of `Client`, so we'd want to mimic the method signatures to keep them consistent.

**Comment by AadamZ5** [comment]
@dcantu476 
> @AadamZ5 Just sharing my thoughts: A shared interface / or base class could tighten up things here for sure. However, the drawback is we are only targeting a single implementation of a method on the class since SearchClient only has one public operation: `collections().`

That's a good point. Making a shared interface just to solve this may be a bit cumbersome. I guess it depends on how strictly typed this lib should be.

Another approach I considered is `extends`. If `SearchClient` is a subset of `Client`, (it might not be) would it be more appropriate for `Client` to extend `SearchClient`?

```typescript
class Client extends SearchClient {

  constructor(options: ConfigurationOptions) {
    super(options);
  }

  ... <more methods and overrides>

}
```

What do you think?

------


Also @jasonbosco
> So I guess calling SearchClient a subset of Client is technically not accurate - I really meant to say, feature-wise SearchClient **only allows search operations to be performed**, whereas Client allows all operations

@jasonbosco This is something I found just a little confusing when using the `SearchClient` class. Both client classes return the same class type `Collection` (normal `Client` can return `Collections` too) which in turn has the same method signature for `Collection.documents()`, which exposes methods for all types of operations. This is confusing since `SearchClient` gave me the impression that it would only allow me to search the collections, yet it has typing that suggests otherwise. Am I just misunderstanding the meaning of the name `SearchClient`, or is this a larger typing issue to discuss in another issue? I will note that I haven't gone as far as to try and actually do a delete operation on a document using the `SearchClient`, but considering it returns the same type, I assume it would let me.

**Comment by jasonbosco** [comment]
@AadamZ5 You bring up a very good point! `SearchClient` is only meant to have these two method signatures:

```js
searchClient.collections('name').documents().search(params)
searchClient.multiSearch.perform(params)
```

So now that I think about it, `searchClient.collections(name)` shouldn't be returning the same `Collection` object as `client.collections(name)`. It should instead return a new object called say `SearchOnlyCollection` which implements a `documents()` method which returns a new object called `SearchOnlyDocuments` which only has the `search()` method. 

What do you think?

**Comment by AadamZ5** [comment]
@jasonbosco That sounds like a good solution. The only thing I am worried about, is if `SearchOnlyDocuments` will be a subset of `Documents`, how will we tell the type-system that?

<details>
<summary>Pardon me for this very long comment. Over-engineering ahead ⚠</summary>
<br>
This brings me back to an interface approach.

Lets look in the case of the `Documents<T>` class

We have these actions
 - `create(...)` _- Only on `Client`_
 - `createMany(...)` _- Only on `Client`_
 - `upsert(...)` _- Only on `Client`_
 - `delete(...)` _- Only on `Client`_
 - `import(...)` _- Only on `Client`_
 - `export(...)` _- Only on `Client`_
 - `search(...)`

I think that we can break these down into a handful of interfaces. I don't think one for every action, but maybe something like this:

```typescript
//For a documents collection that can be searched
interface SearchableDocuments<T> {

  search(...): Promise<SearchResponse<T>>;

}

//For a documents collection that can be operated on
interface CrudDocuments<T> {

  create(...): Promise<T>;
  upsert(...): Promise<T>;
  update(...): Promise<T>;
  delete(...): Promise<DeleteResponse | T>

  //Maybe `import` + `export` functions are defined here too
  //Or they have their own interface below
}

//For a documents collection that can be imported + exported
interface PortableDocuments<T> {

  import(...): Promise<string | ImportResponse[]>
  export(...): Promise<string>
}
```

Then, we can have common ground with the type-system by implementing certain interfaces into these classes

```typescript

class Documents<T> implements SearchableDocuments<T>, CrudDocuments<T>, PortableDocuments<T> {

  //The class will now need to implement all of the function signatures defined in the interfaces
  //The class can have it's own logic for each signature now.
  ... [all implementations]

}

class SearchOnlyDocuments<T> implements SearchableDocuments<T> {

  //Only implement the functions for searching
  ...
}

```

So now in my code, I can expect a searchable documents object as follows:

```typescript


let documentsToSearch: SearchableDocuments<User>;

documentsToSearch = client.collections('users').documents() //OK
documentsToSearch = searchClient.collections('users').documents() //OK

let documentsToUpdate: CrudDocuments<User>

documentsToUpdate = client.collections('users').documents() //OK
documentsToUpdate = searchClient.collections('users').documents() //TS Compiler error!


```

These interfaces may seem redundant, but where functionality is the same, the signature and return type should be defined in **one spot** so if any return-types/signatures change, the types will propagate up, and you will catch a compiler error during package build, which is better than unintended or inconsistent signatures. This means we don't have to maintain multiple signatures of `search(...)` on each type of documents class.

Here is an example of the compiler error if your function signature doesn't match the one from the interface you're implementing:
```typescript
interface ITest {

  myMethod(): Promise<number>;

};

class Test implements ITest {

  /*
  Property 'myMethod' in type 'Test' is not assignable to the same property in base type 'ITest'.
    Type '() => Promise<string>' is not assignable to type '() => Promise<number>'.
      Type 'Promise<string>' is not assignable to type 'Promise<number>'.
        Type 'string' is not assignable to type 'number'.ts(2416)
  */
  myMethod(): Promise<string> {
    throw new Error('Method not implemented.');
  }


}
```

This sort of interface-based composition can propagate through the library where common functionality exists between the two clients. If this is wayyyy to complicated for this lib, lets not worry about it. 

</details>

If `SearchOnlyDocuments` is not a sub-set of `Documents`, then scrap everything mentioned above 😅

**Comment by dcantu476** [comment]
Thanks again! I'll keep working on it this weekend as I have time. 

>where I wish it was instead mostly top-level,

There are definite trade-offs for either direction. I'm completely a fan of this for public apis, however for internals I think we should continue the path it's currently set at. Eventually, you'll end up with so many imports on the same line that they'll stack anyways. 

```
import { Class1,
    Class2,
    Class3,
    Class4, } from 'the-same-place'
vs.

import { Class1} from 'Class1'
import { Class2} from 'Class2'
import { Class3} from 'Class3'
import {Class 4} from 'Class4'
```

Also, re-exporting these internal files makes it slightly more difficult to find the source if you're just reading the code. When they aren't barreled the path is the location of the file and not an index.ts somewhere.
