### ISSUE TITLE
Too many properties to enumerate when calling documents().import()

### ISSUE THREAD

**Issue by jasonbosco** [typesense/typesense-js#81]
Reported on Slack. 

```
Request #1626169731197: Request to Node 0 failed due to "undefined Too many properties to enumerate"
Request #1626169731197: Sleeping for 0.1s and then retrying request...
Request #1626169731197: Request to Node 0 failed due to "undefined Too many properties to enumerate"
Request #1626169731197: Sleeping for 0.1s and then retrying request...
RangeError: Too many properties to enumerate
    at Function.keys (<anonymous>)
    at ApiCall._callee$ (/home/<>/Documents/dt-site-search/node_modules/typesense/lib/Typesense/ApiCall.js:155:46)
    at tryCatch (/home/<>/Documents/dt-site-search/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/<>/Documents/dt-site-search/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/<>/Documents/dt-site-search/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/<>/Documents/dt-site-search/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/<>/Documents/dt-site-search/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

This happens due to a JS limitation: https://stackoverflow.com/questions/9282869/are-there-limits-to-the-number-of-properties-in-a-javascript-object. This also happens for large arrays of objects for some reason.

Instead of calling JSON.stringify on the entire array of objects [here](https://github.com/typesense/typesense-js/blob/a21d4101bc21fe59e0e85b41e64ba14d6fe88667/src/Typesense/Documents.ts#L192), we could split large arrays into smaller ones, then call JSON.stringify on them individually and then concat them together. So users of the client library don't have to do this themselves.

**Comment by akash-joshi** [comment]
Hey @jasonbosco! Is this issue still up for grabs? Going by the various StackOverflow links on the topic:
- https://stackoverflow.com/questions/9282869/are-there-limits-to-the-number-of-properties-in-a-javascript-object
- https://stackoverflow.com/questions/34430182/too-many-properties-in-a-js-object
- https://stackoverflow.com/questions/9282869/are-there-limits-to-the-number-of-properties-in-a-javascript-object/9283945#9283945

, it seems to be a limit introduced by the user's specific JS environment and the amount of memory available.

Updates to NodeJS or V8 might also increase this limit in the future.

Hence, my suggestion is to put [this line](https://github.com/typesense/typesense-js/blob/a21d4101bc21fe59e0e85b41e64ba14d6fe88667/src/Typesense/Documents.ts#L192) in a `try-catch` and iteratively split the imported dataset into `1/(2^n)` parts till it succeeds.

An example of how such a function would work:

```js
const whileFail = (iteration) => {
  try {
    if (iteration !== 3) {
      throw new Error("Failed");
    }
    return iteration;
  } catch (error) {
      return whileFail(iteration + 1);
  }
};

// returns 3
console.log(whileFail(0))
```

In this case, we would check whether the error type is a `RangeError` which includes the text `Too many properties to enumerate` to check if it's an error we want to return for.

Let me know if I can pick this up, and which dataset to run this against.

**Comment by jasonbosco** [comment]
@akash-joshi Yes, this is up for grabs and that is a very interesting solution! Do you want to do a PR?

**Comment by akash-joshi** [comment]
Oh wait, while writing the code for this, I realized we're running `JSON.stringify` on the `document`, not `documents`. Hence, I believe instead we should send a message to the developer that the dataset they're trying to import is too large, or, try to reduce the number of keys they're adding.

I believe this is some sort of a mistake on the dev's side. Perhaps they're trying to import the dataset as `[[...data]]` instead of `[...data]`, hence the individual documents are being imported as a single document. Otherwise, I'm not sure how they're able to create 65,000+ keys on a single object 😅.

**Comment by jasonbosco** [comment]
@akash-joshi That's a good catch! 65K keys on a single object does sound like a lot. I like the idea of catching this error and showing a friendly error message, and may be pointing people to a stackoverflow issue explaining the underlying issue?

**Comment by akash-joshi** [comment]
@jasonbosco created this PR: https://github.com/typesense/typesense-js/pull/88.

Let me know if you want the error message reworded, etc.

**Comment by jasonbosco** [comment]
Added a comment here: https://github.com/typesense/typesense-js/pull/88#issuecomment-987524666

**Comment by akash-joshi** [comment]
#96 should solve the problem in #88 by [rethrowing any other errors](https://github.com/typesense/typesense-js/pull/96/files#diff-1e0565f0f17e3dfb64595df01f7506e4c30037e834ac03d758198f25e05c397eR211) as well.

**Comment by jasonbosco** [comment]
Thanks @akash-joshi! I've merged it in.

**Comment by skipjack** [comment]
Awesome guys, was running into this quite frequently with some non-indexed properties. The new version of this package not only fixed it but also seemed to potentially speed up loading a bit (at least in our case with ~20k documents).
