### ISSUE TITLE
'expires_at' is missing in the parameter of'generateScopedSearchKey'

### ISSUE THREAD

**Issue by ueda19850603** [typesense/typesense-js#82]
## Description
According to the official website, you can specify'expires_at' when creating a restricted key.
https://typesense.org/docs/0.21.0/api/api-keys.html#generate-scoped-search-key

However, VScode prints a warning because there is no'expires_at' in the TypeScript type definition.

## Steps to reproduce
<img width="908" alt="スクリーンショット 2021-11-09 11 53 44" src="https://user-images.githubusercontent.com/13658114/140853367-09680f94-34a6-49a9-b9ae-db1544598bef.png">
write code

<pre>
import * as Typesense from 'typesense'
async function makeLimitKey () {
  const client = new Typesense.Client({
    nodes: [{
      host: 'samplehost_xxxxx',
      port: 443,
      protocol: 'https'
    }],
    apiKey: 'apikey_secret_xxxxxx',
    connectionTimeoutSeconds: 2
  })
  
  const dangerKey = await client.keys().create({
    'description': 'xxxxxx',
    'actions': ['documents:search'],
    'collections': ['*']
  })
  if (dangerKey.value === undefined) {
    return false
  }
  const expiresAt = dayjs().add(30, 'day').unix()
  
  const limitedKey = client.keys().generateScopedSearchKey(
    dangerKey.value,
    {
      'filter_by': 'roomId:dummyData',
      'expires_at': expiresAt // <= here warning
    }
  )
}
</pre>

## Expected Behavior

No warning is displayed

## Actual Behavior
Warning is displayed

## Metadata

VSCode 1.16.0
TypeScript 4.2.4

**Typsense Version**:
Version 1.0.0

**OS**:

**Comment by jasonbosco** [comment]
Oh yes, thank you for catching that. Will push out a fix shortly.

**Comment by jasonbosco** [comment]
@ueda19850603 Just pushed out v1.0.1 with a fix for this.

**Comment by ueda19850603** [comment]
Thank you for your prompt response.
Are q and query_by required to create a restricted key?
Previously you could create a restricted key without passing q and query_by.


<img width="873" alt="issue" src="https://user-images.githubusercontent.com/13658114/140856973-af6c27d2-84be-4fb2-a8bc-f8cb7d54fab3.png">

**Comment by jasonbosco** [comment]
No q and query_by are not required, they're optional in scoped search keys. This is another bug with the type definitions. I'll push out a fix for this shortly.

**Comment by jasonbosco** [comment]
@ueda19850603 Could you try again in this version: `1.0.2-0`?

**Comment by ueda19850603** [comment]
I confirmed the operation with 1.0.2-0.
It worked fine.
Thank you very much.
