### ISSUE TITLE
The argument type of client.keys () is a string.

### ISSUE THREAD

**Issue by ueda19850603** [typesense/typesense-js#84]
## Description
Official sample code
https://typesense.org/docs/0.21.0/api/api-keys.html#delete-api-key

According to this, the argument of client.keys () is a number.
But TypeScript type definitions require strings

## Steps to reproduce

<img width="895" alt="typed" src="https://user-images.githubusercontent.com/13658114/140873204-1e5b7cb6-6af1-4364-a33f-e2ff8bb8b215.png">

## Expected Behavior
According to the operation manual, it is correct to pass the numerical value.

## Actual Behavior
I get a warning when I pass a number.

## Metadata

**Typsense Version**:
typesense 1.0.2

**OS**:

**Comment by jasonbosco** [comment]
@ueda19850603 Good catch! I've pushed out `v1.0.3-0` with a fix for this.

**Comment by ueda19850603** [comment]
@jasonbosco 
I am impressed with the very quick correction.
I am always grateful for your help.
Confirmed that it was fixed in 1.0.3-0
