### ISSUE TITLE
`SearchResponseHit.highlights` and `SearchResponseFacetCountSchema.counts` has invalid type definitions.

### ISSUE THREAD

**Issue by tugaykaracay** [typesense/typesense-js#91]
## Description

`SearchResponseHit.highlights` and `SearchResponseFacetCountSchema.counts` has invalid type definitions. They should be in array format.

## Metadata

**Typsense Version**: 1.0.3-4

**Comment by nandorojo** [comment]
Here is a fix #129

**Comment by jasonbosco** [comment]
Thank you @nandorojo! I've published this in `v1.4.0-4`.

**Comment by nandorojo** [comment]
Sure thing!

It would be nice to have docs for `facet_counts` by the way.

**Comment by jasonbosco** [comment]
Faceting is covered briefly here: https://typesense.org/docs/0.23.1/api/search.html#facet-results

Were you looking for something else?
