### ISSUE TITLE
TypeError: client.collections(...).documents(...).retrieve is not a function

### ISSUE THREAD

**Issue by joshmossas** [typesense/typesense-js#94]
## Description

Calling `client.collections('some-collection').documents('some-doc-id').retrieve()` throws the following error:

```bash
UnhandledPromiseRejectionWarning: TypeError: client.collections(...).documents(...).retrieve is not a function
```

## Steps to reproduce

Just call the method like specified in the Typesense docs. My code looks like the following:

```ts
export const getDoc = async <T = any>(
    client: Typesense.Client,
    collection: SearchCollection,
    documentId: string
) => client.collections<T>(collection).documents(documentId).retrieve();
```

## Expected Behavior

This method should exist and should get the document associated with the documentId that was passed as outlined in the [retrieve a document section](https://typesense.org/docs/0.22.1/api/documents.html#retrieve-a-document) of the docs

## Actual Behavior

You get a "retrieve() is not a function" type error.

## Metadata

- Typesense v0.22.1
- Typesense-JS v1.0.2
- Node v14.17.0
- Npm v8.3.0

**OS**:
Windows 10

**Comment by jasonbosco** [comment]
@joshmossas Could you double check if the actual `client` being passed into `getDoc` is `Typesense.Client` and not `Typesense.SearchClient`? The latter only supports `document.search()`.

**Comment by joshmossas** [comment]
Yes sir, `Typesense.Client` is being passed into `getDoc`.

**Comment by joshmossas** [comment]
@jasonbosco I figured out the problem. 

I was importing typesense like this:
```ts
import Typesense from 'typesense';

const client = new Typesense.Client({
    // stuff here
})
```

But Typesense has no `export default` so I needed to import it like so.

```ts
import * as Typesense from 'typesense';

const client = new Typesense.Client({
    // stuff here
})

///// or alternatively /////

import { Client } from 'typesense';

const client = new Client({
    // stuff here
});
```

**Comment by jasonbosco** [comment]
Ah interesting! This was unintentional change when we converted to Typescript. Will add a default export to prevent any confusion.

**Comment by jasonbosco** [comment]
Pushed out `v1.1.2` where you should now be able to do 

- `import Typesense from 'typesense'` or 
- `import { Client, SearchClient } from 'typesense'` or
- `import * as Typesense from 'typesense'`

**Comment by ddtbuilder** [comment]
I tried 

> Pushed out `v1.1.2` where you should now be able to do:
> 
> * `import Typesense from 'typesense'` or
> * `import { Client, SearchClient } from 'typesense'` or
> * `import * as Typesense from 'typesense'`

I tried all of these and I can't seem to get the import correct. Using rollup i always get this error:

Error: 'Typesense' is not exported by node_modules/typesense/lib/Typesense.js
